config/routes.rb
Rails.application.routes.draw do

  devise_for :admins


  devise_for :users, 
  			 :path => '', 
  			 :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile', :sign_up => 'registration'},
  			 :controllers => {:omniauth_callbacks => 'omniauth_callbacks',
  			 				  :registrations => 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show]
  resources :photos, only: [:create, :destroy]
  resources :speakers, only: [:create, :destroy]
  resources :sponsors, only: [:create, :destroy]
  resources :images, only: [:create, :destroy]


  
  
  resources :events do 
    resources :tickets
  end

  resources :tickets, :path => 'new-pass' do 
    resources :orders
  end
  
  resources :referrals, :path => 'invitation' do 
    resources :tickets do 
      resources :orders 
    end
  end


resources :events, except: [:edit] do 
  member do 
    get 'sold'
  end
end

resources :users, :path =>"upcoming", only: [:community] do 
  member do 
    get 'community'
  end
end

resources :referrals,:path => 'invitation' do 
  member do 
    get 'mypass'
  end
end


root to: 'pages#home'


  get 'host' => 'pages#home'  
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"
  get '/payout_method' => "users#paypal_payout"
  get 'sindu' => 'supports#sindu'

  #get 'support' => "pages#support"

get '/mara', :to => redirect('/upcoming/13/community')
get '/MARA', :to => redirect('/upcoming/13/community')
get '/Mara', :to => redirect('/upcoming/13/community')


  get 'join' => "joins#new"
  get 'support' => "supports#new"
  resources "joins", only: [:new, :create]
  resources "supports", only: [:new, :create]

require 'sidekiq/web'
mount Sidekiq::Web => "/sidekiq"

  
 
end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
	<script type="text/javascript">
		<% resource.errors.full_messages.each do |msg| %>
			toastr.error('<%= msg %>')	
		<% end %>		
	</script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
	<script type="text/javascript">	
		<% flash.each do |f| %>
			<% type = f[0].to_s.gsub('alert','error').gsub('notice','info')  %>
			<% if f[1].length > 0 %>
				toastr['<%= type %>']('<%= f[1] %>') 
			<% end %>
		<% end %>

	</script>
<% end %>	
<!-- 
flash[:notice] = "Email format is incorrect"
- from the above, notice is f[0] and the string about email format is f[1]
- toastr doesnt have alert and notice so thats why we switched it 
more at - tylergannon/toastr-rails on github

-->

app/views/shared/_nav-bar-login-logout.html.erb
<div></div>

app/views/shared/_navbar-dark.html.erb
    <!-- Preloader
    <div id="loader">
      <div class="centrize">
        <div class="v-center">
          <div id="mask">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
          </div>
        </div>
      </div>
    </div> -->
    <!-- End Preloader-->
    <!-- Navbar-->
    <header id="topnav" class="dark" >
      <div class="container">
        <div class="logo bongo-logo-adjust" >
          <a>
            <%= link_to "BONGOPASS", root_path, class: "navbar-brand bongo-design-white bongo-color-dark logo-light", data: { turbolinks: false } %>
            <%= link_to "BONGOPASS", root_path, class: "navbar-brand bongo-design-white bongo-color logo-dark", data: { turbolinks: false } %>
          </a>
        </div>
        <div class="menu-extras">
          <div class="menu-item">
            <a class="navbar-toggle">
              <div class="lines"><span></span><span></span><span></span>
              </div>
            </a>
          </div>
        </div>
        <div id="navigation" data-onepage="true">
          <% if (!user_signed_in?) %>

            <ul class="navigation-menu nav">
              <li><%= link_to "Help", support_path, data: { turbolinks: false } %>
              </li>
              <li><%= link_to "Log In", new_user_session_path, data: { turbolinks: false }  %>
              </li>
              <li><%= link_to "Sign Up", new_user_registration_path, data: { turbolinks: false }  %>
              </li>
            </ul>

          <% else %>

            <ul class="navigation-menu nav hidden-sm hidden-xs">
              <li><%= link_to "Help", support_path, data: { turbolinks: false }  %>
              </li>
              <li class="has-submenu">
                <a>
                  <% if avatar_url(current_user) %>
                    <%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %>&nbsp; 
                  <% end %>
                  <%= current_user.fullname %>
                </a>
                  <ul class="submenu">                    
                    <% if current_user && current_user.create_permission == "allow" %>
                      <li><%= link_to "My Events", events_path, data: { turbolinks: false }  %></li>
                      <li><%= link_to "My Tickets", purchases_path, data: { turbolinks: false } %></li>
                    <% end %>
                        
                    <li><%= link_to "Log Out", destroy_user_session_path, method: :delete, data: { turbolinks: false }  %></li> 
                  </ul>

                <% if current_user && current_user.create_permission != "allow" %>
                  <li><%= link_to "My Tickets", purchases_path, data: { turbolinks: false }  %></li>
                <% end %>

                <% if current_user && current_user.create_permission == "allow" %>
                  <li><%= link_to "Create Event", new_event_path, data: { turbolinks: false } %></li>
                <% end %>
              </li>
            </ul>

            <ul class="navigation-menu nav hidden-md hidden-lg hidden-xl">
              <% if current_user && current_user.create_permission == "allow" %>
                <li><%= link_to "Create Event", new_event_path, data: { turbolinks: false }  %></li>
                <li><%= link_to "My Events", events_path, data: { turbolinks: false }  %></li>
              <% end %>
              <li><%= link_to "My Tickets", purchases_path, data: { turbolinks: false }  %></li>
              <li><%= link_to "Help", support_path, data: { turbolinks: false }  %></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete, data: { turbolinks: false }  %></li>
            </ul>


          <% end %>
        </div>
      </div>
    </header>
    <!-- End Navbar-->

app/views/shared/_navbar-pink.html.erb
 <% content_for :navbar do %>

   <!-- Preloader
    <div id="loader">
      <div class="centrize">
        <div class="v-center">
          <div id="mask">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
          </div>
        </div>
      </div>
    </div>-->
    <!-- End Preloader-->
    <!-- Navbar-->
    <header id="topnav" class="pink-nav">
      <div class="container">
        <div class="logo bongo-logo-adjust" >
          <a>

            <%= link_to "BONGOPASS", root_path, class: " white-text navbar-brand bongo-design-white nav-height-adjust logo-dark bongo-alignment fw-900 ", data: { turbolinks: false } %>
          </a>
        </div>
        <div class="menu-extras">
          <div class="menu-item">
            <a class="navbar-toggle">
              <div class="lines "><span></span><span></span><span></span>
              </div>
            </a>
          </div>
        </div>
        <div id="navigation" data-onepage="true">
          <% if (!user_signed_in?) %>

            <ul class="navigation-menu nav pink-nav-text">
              <li><%= link_to "Help", support_path, data: { turbolinks: false }, class: "pink-nav-text" %>
              </li>
              <li><%= link_to "Log In", new_user_session_path, data: { turbolinks: false }, class: "pink-nav-text"  %>
              </li>
              <li><%= link_to "Sign Up", new_user_registration_path, data: { turbolinks: false }, class: "pink-nav-text"  %>
              </li>
            </ul>

          <% else %>

            <ul class="navigation-menu nav hidden-sm hidden-xs pink-nav-text">
              <li><%= link_to "Help", support_path, data: { turbolinks: false }, class: "pink-nav-text"  %>
              </li>
              <li class="has-submenu">
                <a class= "pink-nav-text">
                  <% if avatar_url(current_user) %>
                    <%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %>&nbsp; 
                  <% end %>
                  <%= current_user.fullname %>
                </a>
                  <ul class="submenu">                    
                    <% if current_user && current_user.create_permission == "allow" %>
                      <li><%= link_to "My Events", events_path, data: { turbolinks: false }  %></li>
                      <li><%= link_to "My Tickets", purchases_path, data: { turbolinks: false } %></li>
                    <% end %>
                        
                    <li><%= link_to "Log Out", destroy_user_session_path, method: :delete, data: { turbolinks: false }  %></li> 
                  </ul>

                <% if current_user && current_user.create_permission != "allow" %>
                  <li><%= link_to "My Tickets", purchases_path, data: { turbolinks: false }, class: "pink-nav-text"  %></li>
                <% end %>

                <% if current_user && current_user.create_permission == "allow" %>
                  <li><%= link_to "Create Event", new_event_path, data: { turbolinks: false }, class: "pink-nav-text" %></li>
                <% end %>
              </li>
            </ul>

            <ul class="navigation-menu nav hidden-md hidden-lg hidden-xl">
              <% if current_user && current_user.create_permission == "allow" %>
                <li><%= link_to "Create Event", new_event_path, data: { turbolinks: false }  %></li>
                <li><%= link_to "My Events", events_path, data: { turbolinks: false }  %></li>
              <% end %>
              <li><%= link_to "My Tickets", purchases_path, data: { turbolinks: false }  %></li>
              <li><%= link_to "Help", support_path, data: { turbolinks: false }  %></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete, data: { turbolinks: false }  %></li>
            </ul>


          <% end %>
        </div>
      </div>
    </header>
    <!-- End Navbar-->

<% end %>


<style>
  #topnav.scroll .navbar-toggle span {
    background-color: white !important;
  }
</style>

app/views/shared/_navbar.html.erb
    <!-- Preloader
    <div id="loader">
      <div class="centrize">
        <div class="v-center">
          <div id="mask">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
          </div>
        </div>
      </div>
    </div> -->
    <!-- End Preloader-->
    <!-- Navbar-->
    <header id="topnav" >
      <div class="container">
        <div class="logo bongo-logo-adjust" >
          <a>
            <%= link_to "BONGOPASS", root_path, class: "navbar-brand bongo-design-white logo-light", data: { turbolinks: false } %>
            <%= link_to "BONGOPASS", root_path, class: "navbar-brand bongo-design-white bongo-color logo-dark", data: { turbolinks: false } %>
          </a>
        </div>
        <div class="menu-extras">
          <div class="menu-item">
            <a class="navbar-toggle">
              <div class="lines"><span></span><span></span><span></span>
              </div>
            </a>
          </div>
        </div>
        <div id="navigation" data-onepage="true">
          <% if (!user_signed_in?) %>

            <ul class="navigation-menu nav">
              <li><%= link_to "Help", support_path, data: { turbolinks: false } %>
              </li>
              <li><%= link_to "Log In", new_user_session_path, data: { turbolinks: false }  %>
              </li>
              <li><%= link_to "Sign Up", new_user_registration_path, data: { turbolinks: false }  %>
              </li>
            </ul>

          <% else %>

            <ul class="navigation-menu nav hidden-sm hidden-xs">
              <li><%= link_to "Help", support_path, data: { turbolinks: false }  %>
              </li>
              <li class="has-submenu">
                <a>
                  <% if avatar_url(current_user) %>
                    <%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %>&nbsp; 
                  <% end %>
                  <%= current_user.fullname %>
                </a>
                  <ul class="submenu">                    
                    <% if current_user && current_user.create_permission == "allow" %>
                      <li><%= link_to "My Events", events_path, data: { turbolinks: false }  %></li>
                      <li><%= link_to "My Tickets", purchases_path, data: { turbolinks: false } %></li>
                    <% end %>
                        
                    <li><%= link_to "Log Out", destroy_user_session_path, method: :delete, data: { turbolinks: false }  %></li> 
                  </ul>

                <% if current_user && current_user.create_permission != "allow" %>
                  <li><%= link_to "My Tickets", purchases_path, data: { turbolinks: false }  %></li>
                <% end %>

                <% if current_user && current_user.create_permission == "allow" %>
                  <li><%= link_to "Create Event", new_event_path, data: { turbolinks: false } %></li>
                <% end %>
              </li>
            </ul>

            <ul class="navigation-menu nav hidden-md hidden-lg hidden-xl">
              <% if current_user && current_user.create_permission == "allow" %>
                <li><%= link_to "Create Event", new_event_path, data: { turbolinks: false }  %></li>
                <li><%= link_to "My Events", events_path, data: { turbolinks: false }  %></li>
              <% end %>
              <li><%= link_to "My Tickets", purchases_path, data: { turbolinks: false }  %></li>
              <li><%= link_to "Help", support_path, data: { turbolinks: false }  %></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete, data: { turbolinks: false }  %></li>
            </ul>


          <% end %>
        </div>
      </div>
    </header>
    <!-- End Navbar-->