config/routes.rb
Rails.application.routes.draw do

  devise_for :admins


  devise_for :users, 
  			 :path => '', 
  			 :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile', :sign_up => 'registration'},
  			 :controllers => {:omniauth_callbacks => 'omniauth_callbacks',
  			 				  :registrations => 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show]
  resources :photos, only: [:create, :destroy]
  resources :speakers, only: [:create, :destroy]
  resources :sponsors, only: [:create, :destroy]
  resources :images, only: [:create, :destroy]


  
  
  resources :events do 
    resources :tickets
  end

  resources :tickets, :path => 'new-pass' do 
    resources :orders
  end
  
  resources :referrals, :path => 'invitation' do 
    resources :tickets do 
      resources :orders 
    end
  end


resources :events, except: [:edit] do 
  member do 
    get 'sold'
  end
end

resources :users, :path =>"upcoming", only: [:community] do 
  member do 
    get 'community'
  end
end

resources :referrals,:path => 'invitation' do 
  member do 
    get 'mypass'
  end
end


root to: 'pages#home'


  get 'host' => 'pages#home'  
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"
  get '/payout_method' => "users#paypal_payout"
  get 'sindu' => 'supports#sindu'

  #get 'support' => "pages#support"

get '/mara', :to => redirect('/upcoming/13/community')
get '/MARA', :to => redirect('/upcoming/13/community')
get '/Mara', :to => redirect('/upcoming/13/community')


  get 'join' => "joins#new"
  get 'support' => "supports#new"
  resources "joins", only: [:new, :create]
  resources "supports", only: [:new, :create]

require 'sidekiq/web'
mount Sidekiq::Web => "/sidekiq"

  
 
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy 
  has_many :tickets, dependent: :destroy
  ## NEEED TO THROW ABORT HERE BECAUSE IF EVENT GETS DELETED IT CANT DELETE THE TICKETS IF IT HAS ORDERS? 
  has_many :orders, :through => :tickets
  has_many :questions, dependent: :destroy 
  has_many :speakers, dependent: :destroy
  has_many :sponsors, dependent: :destroy
  has_many :images, dependent: :destroy


  accepts_nested_attributes_for :tickets, allow_destroy: true
  accepts_nested_attributes_for :questions, allow_destroy: true, reject_if: proc {|att| att['registration_question'].blank? }
  accepts_nested_attributes_for :speakers, allow_destroy: true, reject_if: proc {|att| att['speaker_name'].blank? }
  accepts_nested_attributes_for :sponsors, allow_destroy: true, reject_if: proc {|att| att['logo'].blank? }

  geocoded_by :location
  after_validation :geocode #, if: :location_changed? 

  after_validation :check_lat
  after_validation :check_long



  validates :event_title, presence: true, length: {maximum:75}
  validates :location, presence: true
  validates :start_date, presence: true
  validates :start_time, presence: true
  validates :end_date, presence: true
  validates :end_time, presence: true
  validates :event_description, presence: true
  validates :organizer_name, presence: true
  validates :organizer_description, presence: true
  validates :event_type, presence: false
  validates :venue, presence: true
  validates :event_currency, presence: true
  validates :reward_fee, presence: true, numericality: {greater_than_or_equal_to: 2.50}



  def to_param 
    "#{id}-25-7b509a4-s59i7l86-#{event_title.parameterize}"
  end

  def check_lat
    unless self.latitude
      geocode
    end
  end

  def check_long
    unless self.longitude 
      geocode
    end
  end




end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :sold]
  before_action :authenticate_user!, except: [:show]
  before_action :is_authorized, only: [:sold]


  def index
    @events = current_user.events
    @bongopass_purchases = Order.all.where(seller: current_user).count(:referral_id)
    @bongopass_actual_sales = Order.all.where(seller: current_user).count
    @total_net_sales = Order.all.where(seller: current_user).sum(:organizer_sales)
    @referral_id_count_array = Order.all.where(seller: current_user).group(:referral_id).where.not("referral_id" => nil).count
    @user = current_user

    @reward_value_array = []
    if @referral_id_count_array
      @referral_id_count_array.each do |id, count|

        amount = Referral.where(id: id).first.order.organizer_set_reward * count 
        @reward_value_array << amount

      end
    end

    @all_rewards_earned = @reward_value_array.inject(0, &:+)
  end


  def show
    @photos = @event.photos 
    @tickets = @event.tickets 
    @speakers = @event.speakers
    @sponsors = @event.sponsors
    @ticket_price_min = @tickets.minimum(:ticket_price)
    @ticket_price_max = @tickets.maximum(:ticket_price)
    @bongopass_fee = 3.50
    @cover_photo = @photos[0].image.url(:original) if @photos.present? 
    @google_maps = "https://maps.google.com/?q=" + URI.encode(@event.location)
    @user = User.where(id: @event.user_id).first
    @organizer_events = Event.all.where(user_id: @user.id).order(:start_date).where('start_date >= ?', Date.today)



    set_meta_tags og: {   
      title:       @event.event_title,
      description: @event.event_description.html_safe,
      type:        'article',
      url:         event_url(@event) #,
      #image:       @photos[0].image.url(:original) if @photos[0].image.url(:original).present? 
        }



  end

  def new
    @event = current_user.events.build
    @event.tickets.build
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save

      #save cover photo
      if params[:images]
        params[:images].each do |image|
          @event.photos.create(image: image)
        end
      end

      #save speaker avatars
      if params[:avatars]
        params[:avatars].each do |avatar|
          @event.speakers.build(avatar: avatar)
        end
      end

      #save sponsor logos
      if params[:logos]
        params[:logos].each do |logos|
          @event.sponsors.create(logo: logo)
        end
      end



      @photos = @event.photos
      @speakers = @event.speakers
      @sponsors = @event.sponsors
      redirect_to event_path(@event), notice: "Saved..."
    else
      render :new 
    end
  end

  def edit
    if current_user.id == @event.user.id
      @photos = @event.photos
      @tickets = @event.tickets
      @questions = @event.questions 
      @speakers = @event.speakers
      @sponsors = @event.sponsors

    else
     redirect_to root_path, notice: "You don't have permission"
   end

  end

  def update

    if @event.update(event_params)
     
     if @event.photos.length < 2
        #save cover photo
        if params[:images]
          params[:images].each do |image|
            @event.photos.create(image: image)
          end
        end 
      end


      redirect_to event_path(@event), notice: "Updated..."

    else

      render :edit
    end

  end





  def sold
    @orders = Order.all.where(seller: current_user).order("created_at DESC")
    @tickets = Ticket.all.where(event_id: @event.id)
    @event_orders = Order.joins(:ticket).where(tickets: { event_id: @event.id })
    @bongopass_purchases = Order.joins(:ticket).where(tickets: { event_id: @event.id }).count(:referral_id)
    @paid_to_attendees = Order.joins(:ticket).where(tickets: { event_id: @event.id }).where.not("referral_id" => nil).sum(:organizer_set_reward)
    
    @event_orders_pdf = Order.joins(:ticket).where(tickets: { event_id: @event.id }).order('LOWER(last_name)')

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Guest List",
               template: "events/sold.pdf.erb",
               locals: {:event_orders => @event_orders_pdf}
      end
    end

  end




  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:event_title, :location, :start_date, :start_time, :end_date, :end_time,
                                    :event_description, :organizer_name, :organizer_description, :event_type,
                                    :facebook_link, :twitter_link, :instagram_link, :venue, :event_currency, :reward_fee,
                                    tickets_attributes: Ticket.attribute_names.map(&:to_sym).push(:_destroy),
                                    questions_attributes: Question.attribute_names.map(&:to_sym).push(:id, :_destroy),
                                    speakers_attributes: Speaker.attribute_names.map(&:to_sym).push(:id, :avatar, :_destroy),
                                    sponsors_attributes: Sponsor.attribute_names.map(&:to_sym).push(:id, :logo, :_destroy),
                                    images_attributes: Image.attribute_names.map(&:to_sym),
                                    photos_attributes: Photo.attribute_names.map(&:to_sym))
    end

    def ticket_params 
      params.require(:ticket).permit(:ticket_type, :ticket_name, :ticket_quantity, :ticket_price, :ticket_description,
                                    :ticket_start_date, :ticket_start_time, :ticket_end_date, :ticket_end_time)

    end

    def is_authorized
      redirect_to root_path, alert: "You don't have permission" unless current_user.id == @event.user_id
    end



end

app/helpers/events_helper.rb
module EventsHelper

end

app/views/events/_sponsor.html.erb
<section>

	<div class="row">	
		<div class="col-md-3 select">

			<div class="form-group">
				<label> Sponsor Logo </label>			
				<%= f.file_field :logo, type: :file %>
			</div>			

		</div>
		
	</div>


	<div class="row">	
		<div class="col-md-3 right">	
			<%= f.hidden_field :_destroy %>
			<%= link_to "Remove", '#', class: 'remove_record btn btn-primary' %>
		</div>
	</div>

</section>

app/views/events/index.html.erb
<%= render 'shared/navbar-pink'%>

<section class="pt-0 bbnone">


<div class="container center width-container">
<div class="row">

	<div class="col-md-5ths col-sm-12 col-xs-12 boxed-gray">
		<div class="boxed-text">
			<div class="box-data">
				<%= @events.count %>
			</div>
			<div class="box-description">
			TOTAL EVENTS
			</div>
		</div>
	</div>

	<div class="col-md-5ths col-sm-12 col-xs-12 boxed-gray">
		<div class="boxed-text">
			<div class="box-data">
				<%= @bongopass_actual_sales %>
			</div>
			<div class="box-description">
			TOTAL SALES
			</div>
		</div>
	</div>

	<div class="col-md-5ths col-sm-12 col-xs-12 boxed-gray">
		<div class="boxed-text">
			<div class="box-data event-index-box-padding-adjust">
				<%= @bongopass_purchases %>
			</div>
			<div class="box-description">
			SALES MADE BY YOUR ATTENDEES
			</div>
<!-- After an attendee purchases a ticket they have access to a personalized bongopass page to share with friends. This is the total count of purchases from all of your attendees' bongopass pages -->
		</div>
	</div>

	<div class="col-md-5ths col-sm-12 col-xs-12 boxed-gray ">
		<div class="boxed-text">
			<div class="box-data event-index-box-padding-adjust-2 ">
				<%= number_to_currency(@all_rewards_earned) %>
			</div>
			<div class="box-description">
			PAID TO YOUR ATTENDEES
			</div>
		</div>
	</div>

	<div class="col-md-5ths col-sm-12 col-xs-12 boxed-gray boxed-offset">
		<div class="boxed-text">
			<div class="box-data">
				<%= number_to_currency(@total_net_sales) %>
			</div>
			<div class="box-description">
			TOTAL NET SALES
			</div>
		</div>
	</div>	
</div>

		<div class="com-float-right com-float-right-mobile">
			<%= link_to community_user_path(@user), data: { turbolinks: false }, target: :_blank  do %> 
				<h4 class="new-window-button index-my-community">
					VIEW MY COMMUNITY PAGE <i class="ti-new-window"></i>
				</h4> 
			<% end %>
		</div>

<br>
<br>

<div class="container mobile-container-adjust-eindex">	
<div class="index-event-container">
	<div class=" panel-default">
	<div class="index-event-header index-event-header-adjust">
		<h3 class="index-my-events mb-0">My Events</h3>
		<div class="com-float-right">
			<%= link_to community_user_path(@user), data: { turbolinks: false }, target: :_blank  do %> 
				<h4 class="new-window-button index-my-community">
					VIEW MY COMMUNITY PAGE <i class="ti-new-window"></i>
				</h4> 
			<% end %>
		</div>
	</div>

		<div class="panel-body">
			
			<% @events.order(:start_date).reverse.each do |event| %>
				<div class="row event-row">

					<div class="col-xs-2 p-0 col-md-1 div-button-drop-wrap">
						<div class="">
						  <div class="dropdown">
						    <button class="btn btn-primary dropdown-toggle gear-dropdown-wrapper" type="button" data-toggle="dropdown">
						    	<i class="ti-settings dropdown-gear"></i>
						   	</button>
						    <ul class="dropdown-menu">
						      <li><%= link_to "Update", edit_event_path(event), class: "dmenu-options", data: {turbolinks: false}%></li>
						      <li><%= link_to "View", event_path(event), class: "dmenu-options", data: {turbolinks: false}%></li>
						      <li><%= link_to "Sales", sold_event_path(event), class: "dmenu-options", data: {turbolinks: false}%></li>
						    </ul>
						  </div>
						</div>
					</div>

					<div class="col-xs-10 pr-0 col-md-11 event-row-large">
						<div class="col-md-8 index-event-title pr-0">
							<h4 class="index-event-title"> <%= event.event_title %></h4>
							<h4> <%= event.start_date.to_time.strftime('%A, %B %d') %></h4>
						</div>


						<div class="col-md-4 pr-0">
							<h4> <%= Order.joins(:ticket).where(tickets: { event_id: event.id }).count %>/<%= Order.joins(:ticket).where(tickets: { event_id: event.id }).count + event.tickets.where(event_id: event.id).sum(:ticket_quantity) %> Sold - <%= number_to_currency(Order.joins(:ticket).where(tickets: { event_id: event.id }).sum(:organizer_sales)) %> 
							</h4>
							<div class="event-progress">
							  <div class="event-progress-bar" role="progressbar" style="width: <%= number_to_percentage(Order.joins(:ticket).where(tickets: { event_id: event.id }).count.to_f / (Order.joins(:ticket).where(tickets: { event_id: event.id }).count + event.tickets.where(event_id: event.id).sum(:ticket_quantity))*100) %>"  aria-valuemin="0" aria-valuemax="100"></div>
							</div>							

						</div>

					</div>






				</div>
			<% end %>
		</div>
	</div>

</div>
</div>
</div>



</section>

<style type="text/css">


</style>

app/views/events/show.html.erb
    
<div class="scroll-raiser" id="highlights"></div>

    <section class="section-adjust">
      <div class="container">
        <div class="row">
        	<div class="col-xs-12 col-sm-12 col-md-12">
	        	<div class="title center">
	              <h4 class="upper "><%= @event.organizer_name %> Presents:</h4>
	              <h3><%= @event.event_title %><span class="red-dot"></span></h3>
	              <hr>
	          </div>
	        </div>

					<div class="col-xs-12 col-sm-12 col-md-12"> <!-- Start of under title row -->

						<div class="col-xs-12 col-sm-6 col-md-4 icon-center">
						  <div class="icon-box-basic icon-box-basic-adjust"><i class="icon-calendar"></i>
                <h3 class="date-location-text fw-400"><%= @event.start_date.strftime('%A, %B %e') %></h3>
                <h5 class="fw-400"><%= @event.start_time.strftime('%l:%M%p') %> - <%= @event.end_time.strftime('%l:%M%p') %></h5>
              </div>
            </div>


            <div class="col-xs-12 col-sm-6 col-md-4 icon-center">
						  <div class="icon-box-basic icon-box-basic-adjust"><i class="icon-map"></i>
                <h3 class="date-location-text fw-400"><%= @event.venue %> </h3>
                <p><a href="#location" data-scroll="true">View Address</a></p>
              </div>
            </div>
          

            <div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-offset-0 col-md-4 icon-center">
						  <div class="icon-box-basic icon-box-basic-adjust"><i class="icon-trophy"></i>
                <h5 class="bp-credit-info mt-0 fw-400">Credit from Bongopass is available for this event </h5>
                <p><a><%= link_to "Learn more", root_path(:anchor => "about"), target: :_blank %></a></p>
              </div>
            </div>

            <% if false %> <!-- related links -->
            <div class="col-xs-12 col-sm-6 col-md-4">
            	<div id="footer" class="icon-box-basic-adjust related-links "> 
						  	<p class="bp-credit-info ">Related Links:</p>
						  	<div class="footer-social social-buttons">
                <ul>
                  <li>
                    <a target="_blank" href="#"><i class="ti-world"></i></a>
                  </li>                	
                  <li>
                    <a target="_blank" href="#"><i class="ti-facebook"></i></a>
                  </li>
                  <li>
                    <a target="_blank" href="#"><i class="ti-twitter-alt"></i></a>
                  </li>
                  <li>
                    <a target="_blank" href="#"><i class="ti-instagram"></i></a>
                  </li>
                </ul>
              </div>
						  </div>
            </div>    
            <% end %>        

	        </div> <!-- End of under title row -->

        </div>
        <!-- end of row                    -->
      </div>
      <!-- end of container                  -->


      <div id="bar" class="scroll-raiser-photo">
     	</div>

    		<div class="bar-section">
    			<a class="bar-headers highlight-tab-color" href="#highlights" data-scroll="true">Highlights</a>
    				<a class="bar-headers" href="#bar" data-scroll="true">Photo</a>

    				<a  data-toggle="modal" data-target="#ticket-modal">
	    				<span class="btn btn-color btn-sm btn-round bar-header-button-left pass-purchase-wrapper  ">
	    					COUNT ME IN   
	    				</span>

    				</a>


            <a class="bar-headers" href="#description" data-scroll="true">Details</a>
            <a class="bar-headers" href="#location" data-scroll="true">Location</a>
        </div>

        <div class="bar-section-mobile">
  				<a  data-toggle="modal" data-target="#ticket-modal">
    				<span class="btn btn-color btn-sm btn-round bar-header-button-left pass-purchase-wrapper  ">
    					COUNT ME IN   
    				</span>

  				</a>	 	
        </div>




    </section>


    <!-- Home Section-->
    <%if @photos.present? %>
    <section id="home" class="splash parallax parallax-remove-red photo-bigs">
      <div>	
					<div class="parallax-bg" data-parallax="scroll" data-image-src= <%= @cover_photo %> > </div>
			</div>
    </section>
        <% else %>
          <div class="photo-request">
            Please upload an event photo. All events on Bongopass require a photo. 
          </div>
        <% end %> 

  <section class="photo-smalls pt-0 pb-0">
    <div class=" cover-photo-mobile-container">
      <div class="cover-photo-container"> 
        <!-- Image -->
        <%if @photos.present? %>
          <%= image_tag @photos[0].image.url(:original), class: "img-responsive cover-photo"%>
        <% end %>
      </div>
    </div>
  </section>
    <!-- end of home section-->

<div class="scroll-raiser" id="description"></div>

    <section id="" class="pb-10 pt-35">
      <div class="container">
        <div class="title center">
          <h4 class="upper line-ting">Description</h4>
        </div>
        <div class="section-content">
          <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center desc-styling">
              <p class="grey-text serif lead-text"><%=  @event.event_description.html_safe %></p>
            </div>
          </div>
          <!-- end of row-->
        </div>
        <!-- end of section content-->
      </div>
      <!-- end of container-->
      <div id="host" class="container">
        <div class="title center">
          <h4 class="upper line-ting">About the Host</h4>
        </div>
        <div class="section-content">
          <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center desc-styling">
              <p class="grey-text serif lead-text"><%= @event.organizer_description.html_safe %></p>
            </div>
          </div>
          <!-- end of row-->
        </div>
        <!-- end of section content-->
      </div>
      <!-- end of container-->
    </section>


<section id="location" class="pt-0 pb-0 bb-0">


			<div class="map-wrapper">

				<div class="location-info-overlay">
					<h4 class="event-venue-map mb-10">
						<%= @event.venue %>
					</h4>
		      <p class="date-location-bold mb-30">
						<%= @event.location %> 
					</p>
					<div>
						<a href=<%= @google_maps %> target="_blank" class="btn btn-color btn-round directions-button"><i class="ti-location-arrow direction-arrow-icon"></i>Directions</a>
          </div>
		    </div>

		    <div id="map"></div>

			</div>


</section>


		    <script>
		      function initMap() {
		        var uluru = {lat: <%= @event.latitude %>, lng: <%= @event.longitude %>};

		        var map = new google.maps.Map(document.getElementById('map'), {
		          zoom: 16,
		          center: uluru,
		          mapTypeControl: false, 
		          fullscreenControl: false,
		          scrollwheel: false,
		          clickableIcons: false
		        });

		        var marker = new google.maps.Marker({
		          position: uluru,
		          map: map
		        });



		      }
		    </script>
		    <script async defer
		    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDCZuSB97-CMBj8v9Q7cLaltM60f-z0MOg&callback=initMap">
		    </script>


      <% if @organizer_events.count > 0 && @organizer_events.first != @event %>
      <section class="dark bbnone pt-50 pb-50">
        <div class="container">
          <div class="title center">
            <h3 class="fw-400 capitalize more-events-by">More Events by <%= @event.organizer_name%></h3>
            <hr>
          </div>
          <div class="section-content">
            <div class="row">
              <div class="col-md-8 col-md-offset-2">
                <div id="testimonials-slider" data-options="{&quot;animation&quot;: &quot;slide&quot;, &quot;directionNav&quot;: true}" class="flexslider nav-outside">
                  <ul class="slides">
                    <% @organizer_events.each do |event| %>
                      <% if event != @event %>
                        <li class="event-block-dark">
                          <blockquote>
                            <h1> <%= event.event_title %><span class="red-dot fs-48"></span></h1>
                            <p><%= event.venue %></p>
                            <p><%= event.start_date.strftime('%A, %B %e') %></p>
                          </blockquote>
                        </li>
                      <% end %>
                    <% end %>
                  </ul>
                </div>

                <div class="mt-50 text-center">
                    <%= link_to "View All", community_user_path(@user), data: { turbolinks: false }, target: :_blank, class: "btn btn-color"  %>
                </div>
              </div>
            </div>
            <!-- end of row-->
          </div>
          <!-- end of section content-->
        </div>
        <!-- end of container-->
      </section>
      <% end %>



  <div class="text-center bottom-verified">
    <span class="bongo-b">B</span> <%= @event.organizer_name %> is a Bongopass verified host 
  </div>







				<div class="modal fade" id="ticket-modal">	
					<div class="modal-dialog">	
						<div class="modal-content">
							<div class="modal-header text-center modal-header-design">
								One ticket maximum per person
								<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><i class="ti-close close-modal"></i></span></button>
							</div>
							

							<div class="modal-body">
								<div class="ticket-info-section">
								<% @tickets.order(:ticket_price).each do |ticket| %>
									<div class="ticket-box clearfix">
									<div class="ticket-name-price-desc">							
										<div class="ticket-name-modal"> <%= ticket.ticket_name %> </div>
										<div class="ticket-name-modal"> 
                      <%= number_to_currency(ticket.ticket_price + @event.reward_fee)%>
                      <span class="currency-price">
                        <%= @event.event_currency %> 
                      </span>
                    </div>
										<p class="mt-10"> <%= ticket.ticket_description if ticket.ticket_description%> </p>	
									</div>
									<div class="text-center"> 
										<% if ticket.ticket_quantity > 0 %>
												<%= link_to "Select", new_ticket_order_path(ticket), class: "btn btn-color btn-round directions-button btn-sm modal-buttons", data: { turbolinks: false } %>
										<% else %>
												<div class="btn btn-color-out btn-round directions-button btn-sm modal-buttons">Sold Out</div>
										<% end %>
									</div>
									</div>
									<hr>
								<% end %>							
								</div>
							</div>
						</div>
					</div>
				</div>





<script type="text/javascript" src="https://d3mfs0x6fskujo.cloudfront.net/jquery.js" ></script> 

app/views/events/sold.html.erb
<% content_for :navbar do %>
<%= render 'shared/navbar-pink'%>
<% end %>

<section class="pt-0 ov-v">

<div class="container center width-container">
<div class="row">

	<div class="col-md-3 col-sm-3 col-xs-12 boxed-gray">
		<div class="boxed-text">
			<div class="box-data">
				<%= @event_orders.count %>
			</div>
			<div class="box-description">
			TOTAL SALES
			</div>
		</div>
	</div>

	<div class="col-md-3 col-sm-3 col-xs-12 boxed-gray">
		<div class="boxed-text">
			<div class="box-data">
				<%= @bongopass_purchases %>
			</div>
			<div class="box-description">
			SALES MADE BY YOUR ATTENDEES
			</div>
<!-- After an attendee purchases a ticket they have access to a personalized bongopass page to share with friends. This is the total count of purchases from all of your attendees' bongopass pages -->
		</div>
	</div>

	<div class="col-md-3 col-sm-3 col-xs-12 boxed-gray">
		<div class="boxed-text">
			<div class="box-data">
				<%= number_to_currency(@paid_to_attendees) %>
			</div>
			<div class="box-description">
			PAID TO YOUR ATTENDEES
			</div>
		</div>
	</div>

	<div class="col-md-3 col-sm-3 col-xs-12 boxed-gray boxed-offset">
		<div class="boxed-text">
			<div class="box-data">
				<%= number_to_currency(@event_orders.sum(:organizer_sales)) %>
			</div>
			<div class="box-description">
			NET SALES / PAYOUT AMOUNT
			</div>
<!-- The total amount Bongopass has credited your attendees. Attendees will be able to use their credits for all future events on Bongopass, including yours! This credit is paid out from Bongopass fees collected from all events on our platform and does not include any of your ticket sales. -->
		</div>
	</div>	
</div>
</div>





<div class="container sold-container">

<p class="guest-list">
	<%= link_to 'Print Guest List', sold_event_path(@event, :format => :pdf), target: :_blank %>
</p>

<div class="sold-summary-wrapper">
	
	<div class="description-title-summary">
		SUMMARY
	</div>


<table class="table sold-summary-table">
  <tr class="sold-ticket-table-header">
    <th class="pass-type-row">Ticket Type</th>
    <th class="sold-net-sales-row">Sold</th>
    <th class="sold-net-sales-row">Net Sales</th>
  </tr>


	<% @tickets.order(:ticket_price).each do |ticket| %>
		  <tr>
    <td> <b><%= ticket.ticket_name %> </b> </td>
    <td> <b><%= ticket.orders.where(ticket_id: ticket.id).count %>/<%= ticket.ticket_quantity + ticket.orders.where(ticket_id: ticket.id).count %></b> </td>
    <td> <b><%= number_to_currency(ticket.orders.where(ticket_id: ticket.id).sum(:organizer_sales)) %></b> </td>
  </tr> 

	<% end %>	
</table>
<div class="net-sales-desc">Net Sales <span class="nsd-lf">=</span> Sale Price <span class="nsd-lf">-</span> Transaction Cost <span class="nsd-lf">-</span> Amount Rewarded to Attendees</div>

</div>


<div class="payout-details-wrapper">


	<div class="payout-details-description">
		<div class="payout-details-title">
			PAYOUT DETAILS
		</div>

		Your payout will be issued via PayPal to <%= @event.user.email %> 3-5 days after the event is over. (Allow 4-5 business days for your payout to arrive). Email Andrew, your account manager at andrew@bongopass.com if you have any questions. 
	</div>


</div>



	<div class="description-title">
		SALES BY TICKET TYPE
	</div>

<% @tickets.order(:ticket_price).each do |ticket| %>
	<div class="sold-ticket-name">	
		<b><%= ticket.ticket_name %> </b>
	</div>


<table class="table passes-table">
  <tr class="sold-ticket-table-header">
    <th>Name</th>
    <th>Purchase Date</th>
    <th>Friends Invited</th>
    <th>Email</th>
  </tr>


	<% ticket.orders.order(:created_at).reverse_order.each do |orders| %>
	<tr class="sold-row">
    <td> <%= orders.first_name %> <%= orders.last_name %> </td>
    <td> <%= orders.created_at.strftime('%b %e') %> </td>
    <td> <%= Order.where(referral_id: orders.referral.id).count if Order.where(referral_id: orders.referral.id).count > 0 %> </td>
    <td class="long-email"> <%= orders.buyer.email %> </td>
  </tr> 

	<% end %>	
</table>

	<br>
<% end %>


</div>


</section>