config/routes.rb
Rails.application.routes.draw do

  devise_for :admins


  devise_for :users, 
  			 :path => '', 
  			 :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile', :sign_up => 'registration'},
  			 :controllers => {:omniauth_callbacks => 'omniauth_callbacks',
  			 				  :registrations => 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show]
  resources :photos, only: [:create, :destroy]
  resources :speakers, only: [:create, :destroy]
  resources :sponsors, only: [:create, :destroy]
  resources :images, only: [:create, :destroy]


  
  
  resources :events do 
    resources :tickets
  end

  resources :tickets, :path => 'new-pass' do 
    resources :orders
  end
  
  resources :referrals, :path => 'invitation' do 
    resources :tickets do 
      resources :orders 
    end
  end


resources :events, except: [:edit] do 
  member do 
    get 'sold'
  end
end

resources :users, :path =>"upcoming", only: [:community] do 
  member do 
    get 'community'
  end
end

resources :referrals,:path => 'invitation' do 
  member do 
    get 'mypass'
  end
end


root to: 'pages#home'


  get 'host' => 'pages#home'  
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"
  get '/payout_method' => "users#paypal_payout"
  get 'sindu' => 'supports#sindu'

  #get 'support' => "pages#support"

get '/mara', :to => redirect('/upcoming/13/community')
get '/MARA', :to => redirect('/upcoming/13/community')
get '/Mara', :to => redirect('/upcoming/13/community')


  get 'join' => "joins#new"
  get 'support' => "supports#new"
  resources "joins", only: [:new, :create]
  resources "supports", only: [:new, :create]

require 'sidekiq/web'
mount Sidekiq::Web => "/sidekiq"

  
 
end

app/models/order.rb
class Order < ApplicationRecord
	
	belongs_to :ticket 

	belongs_to :buyer, class_name: "User"
	belongs_to :seller, class_name: "User"

	has_one :referral

	validates :first_name, :last_name, presence: true 
	validate :quantity_available 

	after_create :decrement_quantity
	after_create :create_referral 
	

	def quantity_available
		if ticket.ticket_quantity == 0 
			self.errors.add(:base, "This Pass has sold out")
		end
	end


	def decrement_quantity
		self.ticket.update_attribute("ticket_quantity", (ticket.ticket_quantity - 1))
	end


	def create_referral
      referral = Referral.create(order_id: self.id)
    end


	
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include CurrentReferral 
  #before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :already_purchased, only: [:create]
  before_action :calculate_rewards, only: [:purchases, :create, :new]
  

  def sales 
    @orders = Order.all.where(seller: current_user).order("created_at DESC")
  end


  def purchases 
    
  end



  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
   # @bongopass_fee =3.50
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @ticket = Ticket.find(params[:ticket_id])
    @bongo_fee = 0.99
    @order.referral_id = session[:referral]
    @referral = Referral.find(session[:referral]) if session[:referral]

    #calculate how much rewards are used 
    if @net_rewards_available >= @ticket.ticket_price
      @order.rewards_used = @ticket.ticket_price 
    elsif @net_rewards_available == 0 
      @order.rewards_used = 0 
    else 
      @order.rewards_used = @net_rewards_available 
    end

    @payment_amount = (@ticket.ticket_price - @order.rewards_used) + @ticket.event.reward_fee + @bongo_fee

  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @ticket = Ticket.find(params[:ticket_id])
    @seller = @ticket.event.user 

    @order.ticket_id = @ticket.id 
    @order.buyer_id = current_user.id 
    @order.seller_id = @seller.id 

    @order.bongo_fee = 0.99 
    @bongo_fee = 0.99
    @order.stripe_fee = (@ticket.ticket_price + @ticket.event.reward_fee + @bongo_fee) * 0.029 + 0.3 
    @order.organizer_set_reward = @ticket.event.reward_fee

    
    

    #calculate how much rewards are used 
    if @net_rewards_available >= @ticket.ticket_price
      @order.rewards_used = @ticket.ticket_price 
    elsif @net_rewards_available == 0 
      @order.rewards_used = 0 
    else 
      @order.rewards_used = @net_rewards_available 
    end

    
    @referral = Referral.find(session[:referral]) if session[:referral]

    if @referral 
      if @referral.order.ticket.event_id == @ticket.event_id 
        @order.referral_id = session[:referral]
      end
    end

    if @referral && @referral.order.ticket.event_id == @ticket.event_id
        @order.organizer_sales = @ticket.ticket_price - @order.stripe_fee
    else
      @order.organizer_sales = @ticket.ticket_price + @ticket.event.reward_fee - @order.stripe_fee
    end
  


unless @ticket.ticket_quantity == 0 
  Stripe.api_key = ENV["STRIPE_API_KEY"]
     token = params[:stripeToken]
 
     begin
       charge = Stripe::Charge.create(
         :amount => ((@ticket.ticket_price * 100).floor + (@ticket.event.reward_fee * 100).floor - (@order.rewards_used * 100).floor) + (@order.bongo_fee * 100).floor,
         :currency => @ticket.event.event_currency,
         :description => "Example charge",
         :source => token
         #:receipt_email => "andrew.selvadurai6@gmail.com",
         #:destination => {
         # :amount => (@ticket.ticket_price * 100).floor - (@order.stripe_fee * 100).floor,
         # :account => @ticket.event.user.merchant_id 
           #}
         )

       if charge
          OrderMailer.send_email_to_buyer(@order.buyer, @ticket.event).deliver_later
        end
       flash[:notice] = "Thanks for ordering!"

        rescue Stripe::CardError => e
        flash[:error] = e.message
        return redirect_to new_ticket_order_path

     end
end

       respond_to do |format|
            if @order.save
              format.html { redirect_to mypass_referral_path(@order.referral) }
              format.json { render :show, status: :created, location: @order }
            else
              format.html { render :new }
              format.json { render json: @order.errors, status: :unprocessable_entity }
            end
            end

    end





  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:first_name, :last_name)
    end

    def update_inventory
      @ticket.ticket_quantity - 1 
    end

    #People can still buy another type of ticket for that event if the event has multiple tickets 
    def already_purchased 
      @ticket = Ticket.find(params[:ticket_id])
      unless Order.joins(:ticket).where(buyer_id: current_user.id).where(ticket_id: @ticket.id).blank?
        redirect_to new_ticket_order_path, notice: "You can only purchase one Pass for this event"
      end
    end


    def calculate_rewards
    @orders = Order.all.where(buyer: current_user).order("created_at DESC")
    @all_rewards_used = 0 
    @net_rewards_available = 0


    if @orders 
      @rewards_used_array = []
      @orders.each do |order|
        ching = order.rewards_used
        @rewards_used_array << ching 
      end

      @all_rewards_used = @rewards_used_array.inject(0, &:+)
    end

    #GETS ALL THE REFERRAL_IDS THAT BELONG TO THE USER, SINCE @ORDERS ARE THE USERS ORDERS
    if @orders 
    @referral_id = []
      @orders.each do |order|
        ting = order.referral.id 
        @referral_id << ting 
      end
    

    #COUNTS THE NUMBER OF TIMES THAT REFERRAL ID IS USED
    @something = Order.where(referral_id: @referral_id).group(:referral_id).count

    #TAKES THE REFERRAL ID AND COUNT AND MULTIPLIES IT BY WHATEVER THE REWARD FEE IS FOR THAT EVENT
    @reward_value_array = []
    if @something 

      @something.each do |id, count|
        amount = Referral.where(id: id).first.order.organizer_set_reward * count 
        @reward_value_array << amount

      end
    end

    @all_rewards_earned = @reward_value_array.inject(0, &:+)

    @net_rewards_available = @all_rewards_earned - @all_rewards_used
  end

  end




end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
    <section class="pt-35">
      <div class="container">
          <div class="checkout-form">
            <div class="row">

              <div class="col-md-5 mb-30"> <!-- left side -->

                <div class="text-center">
                  <h3><%= @ticket.event.event_title %></h3>
                  <h4>Ticket Name: <%= @ticket.ticket_name %></h4>
                </div>
                <div class="wrapting">
                <div class="price-credit-wrapper">
                  <div class="price-credit-title">
                    <h5 class="price-title">Price</h5>
                    <h5 class="credit-title">Fee</h5>
                    <h5 class="credit-title">Credit Applied</h5>
                  </div>

                  <div class="price-credit-data">
                    <h5><%= number_to_currency(@ticket.ticket_price + @ticket.event.reward_fee) %></h5>
                    <h5><%= number_to_currency(@bongo_fee) %></h5>
                    <h5><span class="minus-sign">-</span><%= number_to_currency(@order.rewards_used) %> </h5> 
                  </div>
                </div>

                <div class="total-wrapper">
                  <div class="total-title">
                     <h5 class="total-title-text">Total</h5>
                  </div>
                  <div class="total-data">
                    <h5 class="total-data-text"><%= number_to_currency(@payment_amount) %> </h5>
                  </div>
                </div>

                <% if (@payment_amount - @bongo_fee) == @ticket.event.reward_fee %>
                  <div class="minimum-amount">
                    There is a minimum price limit of <%= number_to_currency(@ticket.event.reward_fee) %> for this event.
                  </div>
                <% end %>
                </div>

                <h6 class="fw-600 fine-print">
                  Delivery Method 
                </h6>

                <h6 class="fw-300">
                  Will Call: Please arrive at the venue with your photo ID and confirmation email. 
                </h6>

                <h6 class="fw-600 fine-print">
                  Refund Policy 
                </h6>

                <h6 class="fw-300">
                  No refunds.
                </h6>

                <h6 class="fw-600 fine-print">
                  Purchase Limit
                </h6>

                <h6 class="fw-300">
                  One ticket per attendee.
                </h6>

              </div>



              <div class="col-md-5 col-md-offset-1"> <!-- right side -->
              <%= form_for([@ticket, @order]) do |form| %>
                <% if order.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

                    <ul>
                    <% order.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>

                <div id="stripe_error" class="alert alert-danger" style="display:none">
                  <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
                </div>

                <div class="title">
                  <h5 class="upper fw-600">Full Name of Attendee</h5>
                  <hr>
                </div>
                <div class="form-group">
                  <%= form.text_field :first_name, id: :first_name, placeholder: "First Name", class: "form-control order-form-inputs", required: true %>
                </div>
                <div class="form-group">
                  <%= form.text_field :last_name, id: :last_name, placeholder: "Last Name", class: "form-control order-form-inputs", required: true %>
                </div>
                <div class="title">
                  <h5 class="upper fw-600">Credit Card Info</h5>
                  <hr>
                </div>

                <div class="form-group">
                  <%= text_field_tag :card_number, nil, { :name => nil, :'data-stripe' => "number", class: "form-control order-form-inputs", placeholder: "Credit Card Number" } %>
                </div>
                <div class="form-group">
                  <div class="col-xs-4 pl-0">
                    <%= text_field_tag :card_code, nil, { :name => nil, :'data-stripe' => "cvc", class: "form-control order-form-inputs", required: true, placeholder: "CVC" } %>
                  </div>
                  <div class="col-xs-4 pl-0">
                    <%= select_month nil, { use_two_digit_numbers: true }, { :name => nil, :'data-stripe' => "exp-month", class: "form-control order-form-inputs", placeholder: "Month" } %>
                  </div>
                  <div class="col-xs-4 p-0">
                    <%= select_year nil, { start_year: Date.today.year, end_year: Date.today.year+10 }, { :name => nil, :'data-stripe' => "exp-year", class: "form-control order-form-inputs", placeholder:"Year" } %>
                  </div>
                </div>
                <div class="form-group">
                  <%= text_field_tag :postal_code, nil, { :name => nil, :'data-stripe' => "address-zip", class: "form-control order-form-inputs", required: true, placeholder: "Zip Code" } %>
                </div>
                <div class="form-group">
                  <div class="row">
                    <div class="col-xs-6">
                      <h5 class="upper">Order Total</h5>
                    </div>
                    <div class="col-xs-6 text-right">
                      <h5><%= number_to_currency(@payment_amount) %></h5>
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <div class="checkout-submit">
                    <%= form.submit "Complete Order", class: "btn btn-color btn-block order-form-inputs" %>
                  </div>
                </div>
              <% end %>
              </div>
            </div>
            <!-- end of row-->
          </div>
      </div>
    </section>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>City</th>
      <th>Province</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.address %></td>
        <td><%= order.city %></td>
        <td><%= order.province %></td>
        <!--
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', event_orders_path %>

app/views/orders/new.html.erb
<%= render 'form', order: @order %>

<!-- <%= link_to 'Back', event_path(@ticket.event) %> -->

app/views/orders/purchases.html.erb
    <section class="page-title parallax purchases-parallax mb-50">
      <div data-parallax="scroll" class="parallax-bg"></div>
      <div class="parallax-overlay purchases-overlay-actual">
        <div class="centrize">
          <div class="v-center">
            <div class="container">
              <div class="title center">
                <h1 class="upper upper-rewards"><%= number_to_currency(@net_rewards_available) %></h1>
                <h4>BONGOPASS CREDITS AVAILABLE</h4>
                <hr>
              </div>
            </div>
            <!-- end of container-->
          </div>
        </div>
      </div>
    </section>

<div class="">	
<div class="">





<div class=" panel-default col-xs-12 col-sm-12 col-md-8 col-md-offset-2 bp-passes-purchased ">


	<h3 class="create-event-header my-passes-title">
		<div class="">MY TICKETS</div>
	</h3>

		<% if @orders.count < 1 %>
		<div class="panel-body no-passes">
			You have not purchased any tickets yet.
		</div>


		<% end %>

		<div class="panel-body">
			
			<% @orders.each do |order| %>
				<div class="row purchases-passes">

					<div class="col-md-8 col-sm-12 passes-details">
						<h3 class="purchases-event-title"> <%= order.ticket.event.event_title %> </p>
						<h4 class="purchases-date"> <%= order.ticket.ticket_name %> </h4>
						<h4 class="purchases-date"> <%= order.ticket.event.venue %> </h4>
						<h4 class="purchases-date"> <%= order.ticket.event.start_date.to_time.strftime('%A, %b %d') %> at <%= order.ticket.event.start_time.strftime('%l:%M%p') %> </h4>
					</div>

					<div class="col-md-4 col-sm-12 share-button-wrapper">
						<div>

						<%= link_to "Invite Friends", mypass_referral_path(Referral.find(order.referral.id)), class:"btn btn-color btn-block purchases-buttons", data: { turbolinks: false } %>
						</div>

						<div>
						<%= link_to "View My Event Page", referral_path(Referral.find(order.referral.id)), class:"btn btn-dark-out btn-block purchases-buttons", data: { turbolinks: false } %>
						</div>
						
					</div>


				</div>
				<hr>
			<% end %>
		</div>
</div>









</div>
</div>

app/views/orders/sales.html.erb
<div class="container">
	
<% @orders.each do |order| %>
	<div class="row">	
		<%= order.ticket.event.event_title %>
	</div>
	<div class="row">	
		<%= order.buyer.fullname %>
	</div>
	<br>
<% end %>


</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @order.city %>
</p>

<p>
  <strong>Province:</strong>
  <%= @order.province %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>