config/routes.rb
Rails.application.routes.draw do

  devise_for :admins


  devise_for :users, 
  			 :path => '', 
  			 :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile', :sign_up => 'registration'},
  			 :controllers => {:omniauth_callbacks => 'omniauth_callbacks',
  			 				  :registrations => 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show]
  resources :photos, only: [:create, :destroy]
  resources :speakers, only: [:create, :destroy]
  resources :sponsors, only: [:create, :destroy]
  resources :images, only: [:create, :destroy]


  
  
  resources :events do 
    resources :tickets
  end

  resources :tickets, :path => 'new-pass' do 
    resources :orders
  end
  
  resources :referrals, :path => 'invitation' do 
    resources :tickets do 
      resources :orders 
    end
  end


resources :events, except: [:edit] do 
  member do 
    get 'sold'
  end
end

resources :users, :path =>"upcoming", only: [:community] do 
  member do 
    get 'community'
  end
end

resources :referrals,:path => 'invitation' do 
  member do 
    get 'mypass'
  end
end


root to: 'pages#home'


  get 'host' => 'pages#home'  
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"
  get '/payout_method' => "users#paypal_payout"
  get 'sindu' => 'supports#sindu'

  #get 'support' => "pages#support"

get '/mara', :to => redirect('/upcoming/13/community')
get '/MARA', :to => redirect('/upcoming/13/community')
get '/Mara', :to => redirect('/upcoming/13/community')


  get 'join' => "joins#new"
  get 'support' => "supports#new"
  resources "joins", only: [:new, :create]
  resources "supports", only: [:new, :create]

require 'sidekiq/web'
mount Sidekiq::Web => "/sidekiq"

  
 
end

app/views/pages/home.html.erb
    <!-- Home Section-->
    <section id="home" class="splash parallax landing-splash">
      <div data-parallax="scroll" data-image-src="https://s3.ca-central-1.amazonaws.com/bongopass/austin-neill-247047-2+copy.jpg" class="parallax-bg"></div>
      <div class="centrize">
        <div class="v-center">
          <div class="container">
            <div class="row">
              <div class="col-md-8">
                <div class="title">
                  <h2 class="fw-600 great-experiences">Great Experiences Together</h2>
                  <p class="landing-page-explainer fw-500">Bongopass is the world's first social events platform that enables event hosts to share their profits with attendees. Through Bongopass, attendees are rewarded for helping friends discover new experiences - giving attendees and hosts the ability to work together in the making of great events.</p> 
                  <p class="landing-height-adjust">
                  	<a href="#about" data-scroll="true" class="btn btn-light btn-round landing-how-it-works landing-buttons">How it works<i class="ti-control-play"></i></a>
                  	<a class=""><%= link_to "Become a host", join_path, class: "btn btn-light-out btn-round landing-buttons", data: { turbolinks: false } %> </a>
                  </p>
                </div>
              </div>
            </div>
            <!-- end of row-->
          </div>
          <!-- end of container-->
        </div>
      </div>
    </section>
    <!-- end of home section-->

    <section id="about">
      <div class="container">
      <div class="title center">
          <h4 class="upper">How Bongopass Works - attendees</h4>
          <h2 class="fw-500">Welcome to the future of events<span class="red-dot"></span></h2>
          <hr>
        </div>
        <div class="section-content">
          <div class="row">

            <div class="col-sm-4">
              <div class="icon-box-small  mb-25"><i class="ti-comment-alt"></i><span class="back-icon"><i class="ti-comment-alt"></i></span>
                <hr>
                <h4>1. Share your link</h4>
                <p class="how-works-text-box">After you purchase a ticket to an event, you will receive a unique event link. Share your link with friends or post it on social media to easily invite others to the same event.</p>
              </div>
              <!-- end of icon box-->
            </div>

            <div class="col-sm-4">
              <div class="icon-box-small boxed mb-25"><i class="icon-trophy"></i><span class="back-icon"><i class="icon-trophy"></i></span>
                <hr>
                <h4>2. Receive credit</h4>
                <p class="how-works-text-box">Bongopass credits your account for each friend that purchases a ticket from your unique event link.</p>
              </div>
              <!-- end of icon box-->
            </div>



            <div class="col-sm-4">
              <div class="icon-box-small outlined mb-25"><i class="icon-wallet"></i><span class="back-icon"><i class="icon-wallet"></i></span>
                <hr>
                <h4>3. Use Credit</h4>
                <p class="how-works-text-box">Use your credit to go to any future event for free!</p>
              </div>
              <!-- end of icon box-->
            </div>

          </div>
          <!-- end of row-->
        </div>
        <!-- end of section content-->
      </div>
      <!-- end of container-->
    </section>


    <section class="dark blue-landing">
      <div class="container">
        <div class="title center">
          <h4 class="upper fw-600">Built for you.</h4>
          <h2 class="fw-500">Quality Events<span class="red-dot"></span></h2>
          <hr>
        </div>
        <div class="section-content">
          <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center">
              <p class="grey-text serif lead-text raleway-font-fam fw-500 ">From college and university parties to music concerts, we've found the perfect formula for the ultimate social experience.</p>
            </div>
          </div>
          <!-- end of row-->
        </div>
        <!-- end of section content-->
      </div>
      <!-- end of container-->
    </section>


    <!-- Footer-->
    <footer id="footer-widgets">
      <div class="container">
        <div class="go-top">
          <a href="#top">
            <i class="ti-arrow-up"></i>
          </a>
        </div>
        <div class="row">
          <div class="col-md-6 ov-h">
            <div class="row">
              <div class="col-sm-4">
                <div class="widget">
                  <h6 class="upper">Contact</h6>
                  <p>
                    <span>Every email is replied to within 24 hours.</span>
                    <span><%= mail_to "support@bongopass.com" %></span>
                  </p>
                </div>
              </div>

            </div>
          </div>
          <div class="col-md-4 col-md-offset-2">
            <div class="row">
              <div class="col-md-12">
                <div class="widget">
                  <h6 class="upper">Stay in touch</h6>
                  <p>Sign up to get early access to new features.</p>
                  <div class="footer-newsletter">
                    <form class="inline-form">
                      <div class="input-group">
                        <input type="email" name="email" placeholder="Your Email" class="form-control"><span class="input-group-btn"><button type="submit" data-loading-text="Loading..." class="btn btn-color">Signup</button></span>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- end of row-->
      </div>
      <!-- end of container-->
    </footer>
    <footer id="footer">
      <div class="container">
        <div class="footer-wrap">
          <div class="row">
            <div class="col-md-4">
              <div class="copy-text">
                <p><i class="icon-heart red mr-15"></i>© 2018 Bongopass.</p>
              </div>
            </div>
            <!--
            <div class="col-md-4">
              <ul class="list-inline">
                <li>
                  <a href="#">About</a>
                </li>
                <li>
                  <a href="#">Services</a>
                </li>
                <li>
                  <a href="#">Blog</a>
                </li>
                <li>
                  <a href="#">Contact</a>
                </li>
              </ul>
            </div>
          -->

          </div>
          <!-- end of row-->
        </div>
      </div>
      <!-- end of container-->
    </footer>
    <!-- end of footer-->

app/views/pages/support.html.erb
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,600,700" rel="stylesheet">


<div class="container">
	<h1 class="support-header">
		Support
	</h1>

<div class="row">
 <div class="col-sm-12 col-lg-4 col-md-4 col-xs-12">
 	<h2 class="question-headers">
 		Most Frequently Asked 
 	</h2>

	<div class="trams-conditions">
	  <div href="#" id="toggle2" class="fa fa-plus question-wrapper">
	  	<div class="question-answer"> 

	  	<h4 class="support-question"> 
		  	What is Bongopass?
		</h4>

			<p class="trams-con">
				Bongopass is a live events platform that partners with established artists, DJs, venues, and event organizers to bring our community awesome live experiences. We share up to 90% of our profits with our attendees to make it easier for people to discover great events through their friends. 
				<br>
				<br>
				When you help others discover great experiences on Bongopass we enable you to go to future events for free. That's why events are always more awesome on Bongopass! 
			</p>
		</div>
	  </div>
	</div>

	<div class="trams-conditions">
	  <div href="#" id="toggle2" class="fa fa-plus question-wrapper">
	  	<div class="question-answer"> 

	  	<h4 class="support-question"> 
		  	How do Bongopass credits work?
		</h4>

			<p class="trams-con">
				Events on Bongopass are only as awesome as the people that go to it. So after you purchase a Pass on Bongopass we share our profits with you for helping others discover a great experience. Bongopass will credit your account with $10 for every 3 passes purchased on your Personal Event Page, up to a maximum of $100. You can find your Personal Event Page and track your credits under "My Passes".
			</p>
		</div>
	  </div>
	</div>

	<div class="trams-conditions">
	  <div href="#" id="toggle2" class="fa fa-plus question-wrapper">
	  	<div class="question-answer"> 

	  	<h4 class="support-question"> 
		  	I have paid for my Pass but did not receive an email confirmation. What should I do?
		</h4>

			<p class="trams-con">
				If your payment was processed, you can find your Pass under "My Passes". If your Pass is there, don't worry you'll get in to the event as long as you bring a verified government ID. If your Pass is not there, your payment was not successful so please try again. 
			</p>
		</div>
	  </div>
	</div>

	<div class="trams-conditions">
	  <div href="#" id="toggle2" class="fa fa-plus question-wrapper">
	  	<div class="question-answer"> 

	  	<h4 class="support-question"> 
		  	How do I host events with Bongopass?
		</h4>

			<p class="trams-con">
				If you are an established artist, DJ, venue, or event organizer, we'd love to work with you. Apply <a href="/joins">here</a>. 
			</p>
		</div>
	  </div>
	</div>

</div>

 <div class="col-sm-12 col-lg-4 col-md-4 col-xs-12">
 	<h2 class="question-headers">
 		Passes
 	</h2>

	<div class="trams-conditions">
	  <div href="#" id="toggle2" class="fa fa-plus question-wrapper">
	  	<div class="question-answer"> 

	  	<h4 class="support-question"> 
		  	What do I bring to the event after I've purchased my Pass?
		</h4>

			<p class="trams-con">
				If you purchased a Pass, all you need to bring is a verified government ID so we know it's you.  
			</p>
		</div>
	  </div>
	</div>

	<div class="trams-conditions">
	  <div href="#" id="toggle2" class="fa fa-plus question-wrapper">
	  	<div class="question-answer"> 

	  	<h4 class="support-question"> 
		  	How many Passes can I purchase to an event?
		</h4>

			<p class="trams-con">
				Everyone is limited to only one Pass type per event. If there are two different Passes to an event, you can purchase one of each. 
			</p>
		</div>
	  </div>
	</div>

	<div class="trams-conditions">
	  <div href="#" id="toggle2" class="fa fa-plus question-wrapper">
	  	<div class="question-answer"> 

	  	<h4 class="support-question"> 
		  	What will others see when I share my personal event page. 
		</h4>

			<p class="trams-con">
				You will receive a personal event page for every Pass you purchase on Bongopass. When you share your personal event page, your friends will see the actual event content and a message letting them know they have been invited by you. They will also be able to see the names of the individuals who have purchased a Pass through your personal event page. 
			</p>
		</div>
	  </div>
	</div>



</div>



 <div class="col-sm-12 col-lg-4 col-md-4 col-xs-12">
 	<h2 class="question-headers">
 		Cancellations
 	</h2>

	<div class="trams-conditions">
	  <div href="#" id="toggle2" class="fa fa-plus question-wrapper">
	  	<div class="question-answer"> 

	  	<h4 class="support-question"> 
		  	Can I change or return my Pass?
		</h4>

			<p class="trams-con">
				Passes are non-refundable, non-transferable and cannot be changed for other Passes, as mentioned on the checkout page. 
			</p>
		</div>
	  </div>
	</div>

	<div class="trams-conditions">
	  <div href="#" id="toggle2" class="fa fa-plus question-wrapper">
	  	<div class="question-answer"> 

	  	<h4 class="support-question"> 
		  	The event was cancelled. What should I do now? 
		</h4>

			<p class="trams-con">
				You will be informed by the event organizer or the Bongopass team about your next steps. In most cases, you will have the choice to be given a refund or attend the event on a rescheduled date. 
			</p>
		</div>
	  </div>
	</div>



</div>
</div>

<p class="contact-for-more-support">
	Didn't find what you were looking for? Contact us at support@bongopass.com
</p>


	<h1 class="support-header">
		Feedback
	</h1>









</div>


<script>
$('#toggle1,#toggle2').click(function() {
  $('.trams-con', this).slideToggle('fast');
  if ($(this).hasClass('fa-minus')) {
    $(this).removeClass('fa-minus').addClass('fa-plus');
  } else {
    $(this).addClass('fa-minus');
  }
  return false;
});
</script>